version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: traderius-zookeeper
    ports:
      - 2181:2181
    logging:
      driver: "none"
  kafka:
    image: wurstmeister/kafka
    container_name: traderius-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "none"
  traider:
    build: ../traider
    container_name: traderius-traider
    depends_on: 
      - kafka
      - zookeeper
    links: 
      - kafka
      - zookeeper