name: notifier-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation and build
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          cd notifier
          npm install
          npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          cd notifier
          npm run static:lint
