name: notifier-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: use notifier
        run: cd notifier
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: lint
        run: npm run static:lint
